### ISSUE TITLE
Story 9

### ISSUE THREAD

**Issue by GavJam80** [GavJam80/TypeRacer#9]
As a competitive user, I want my best results for each difficulty level to be displayed so that I can compare my progress.

**Acceptance Criteria:**

- [ ] The best test result for each level is stored
- [ ] The best test result for each level is displayed on the site

**Tasks:**

- [ ] Create an area to display the best test results for each level of difficulty
- [ ] The best test result for each level is stored and displayed to the user
